export const GET_CHEMICAL_DATA = "GET_CHEMICAL_DATA";
export const SET_CHEMICAL_DATA = "SET_CHEMICAL_DATA";
export const CLEAR_CHEMICAL_DATA = "CLEAR_CHEMICAL_DATA";
export const SET_QUERY = "SET_QUERY";
